urls.py
from django.conf.urls import url
from . import views

app_name = 'personalia'
urlpatterns = [
    url(r'^$',views.index, name='index'),
    url(r'^warga/$',views.warga, name='warga'),
    url(r'^tambahanggota/$',views.tambahWarga, name='tambahWarga'),
    url(r'^laporan/$',views.index, name='laporan'),
    url(r'^pengurus/$',views.index, name='pengurus'),
    url(r'^tambahAdmin/$',views.index, name='tambahAdmin'),
    url(r'^tambahdata/$',views.tambahdata, name='tambahdata',),
]

models.py
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone

class Individu(models.Model):
    PILIH_JK = [
        ('L','Laki-laki'),('P','Perempuan'),
    ]
    PILIH_LULUSAN = [
        ('1','SD'),('2','SMP'),('3','SMA'),('4','D3'),('5','S1'),('6','S2'),('7','S3'),
    ]

    id_individu = models.AutoField(primary_key=True)
    nama = models.CharField(max_length=50,)
    #nama = models.CharField(max_length=50,blank=True,null=True)
    tmpt_lahir = models.CharField(max_length=50,blank=True,null=True)
    tgl_lahir = models.DateField(blank=True,null=True)
    jk = models.CharField(max_length=1,choices=PILIH_JK)
    #jk = models.CharField(max_length=1,choices=PILIH_JK,blank=True,null=True)
    #alamat = models.TextField(max_length=200)
    alamat = models.TextField(max_length=200,blank=True,null=True)
    alamat_desa = models.CharField(max_length=50,blank=True,null=True)
    #alamat_desa = models.CharField(max_length=50)
    alamat_kec = models.CharField(max_length=50)
    alamat_kabkot = models.CharField(max_length=50)
    alamat_prov = models.CharField(max_length=50)
    #lulusan = models.CharField(max_length=3,choices=PILIH_LULUSAN)
    lulusan = models.CharField(max_length=3,choices=PILIH_LULUSAN,blank=True,null=True)
    hp = models.CharField(max_length=15,blank=True,null=True)

    class Meta:
        ordering = ('jk','id_individu','nama',)
        unique_together = ('nama','jk','lulusan')

    def __str__(self):
        return self.nama

class Pangkal(models.Model):
    PILIH_RT = [
        ('ahm','ahmad'),('ksm','kusmawan'),('mgd','migud'),
        ('sdk','sodikin'),('sdr','sodirun'),
    ]

    id_pk = models.CharField(max_length=5,primary_key=True,)
    nama = models.CharField(max_length=50)
    rt = models.CharField(max_length=5,choices=PILIH_RT)

    class Meta:
        ordering = ('rt','id_pk',)

    def __str__(self):
        return self.nama

class Warga(models.Model):
    PILIH_JEN = [
        ('0','WB'),('1','Pra A1'),('2','A1'),('3','A2')
    ]

    PILIH_SA = [
        ('ak','AK'),('pa','PA'),('bk1','BK_1'),('bk2','BK_2'),('bk3','BK_3')
    ]
    PILIH_SEG = [
        ('m','Mahasiswa'),('p','Pelajar'),('u','Umum')
    ]

    id_warga = models.CharField(max_length=10,primary_key=True)
    individu = models.OneToOneField(
        Individu,
        on_delete=models.CASCADE,
    )
    '''jenjang = models.CharField(max_length=1,
        choices=PILIH_JEN)'''
    jenjang = models.CharField(max_length=1,
        choices=PILIH_JEN,blank=True,null=True)
    tgl_daftar = models.DateField(blank=True,null=True)
    #status_aktif = models.CharField(max_length=5,choices=PILIH_SA)
    status_aktif = models.CharField(max_length=5,choices=PILIH_SA,blank=True,null=True)
    #segmentasi = models.CharField(max_length=1,choices=PILIH_SEG)
    segmentasi = models.CharField(max_length=1,choices=PILIH_SEG,blank=True,null=True)
    pangkal = models.ForeignKey(Pangkal, related_name='PangkalDari')
    #pangkal = models.ForeignKey(Pangkal, related_name='PangkalDari',blank=True,null=True)
    warga_media = models.BooleanField(default=False)
    keterangan = models.TextField(max_length=500,blank=True,null=True)
    #tgl_input = models.DateTimeField(default=timezone.now)
    tgl_input = models.DateTimeField(blank=True,null=True)

    class Meta:
        ordering = ('status_aktif','jenjang','id_warga',)

    def __str__(self): # __unicode__ on Python 2
        return '{}'.format(self.individu)

views/tambahdata.py
from personalia.forms import fIndividu
from django.shortcuts import render,redirect
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages

def tambahdata(request):
    template_name = 'personalia/tambahdata.html'
    form = (fIndividu,)

    if request.method == 'POST':
        cekform = fIndividu(request.POST)
        if cekform.is_valid():
            individu = cekform.save()
            messages.add_message(request, messages.SUCCESS, 'Berhasil menambahkan {0} ke dalam data member'.format(individu.nama,))
            return HttpResponseRedirect(reverse('personalia:tambahdata'))
        else :
            form = (cekform,)
            individu = cekform.clean()
            messages.add_message(request, messages.WARNING, 'Gagal menambahkan {0} ke dalam data member'.format(individu['nama'],))

    return render(request,template_name,{'form':form,})

views/warga.py
from __future__ import unicode_literals

from django.shortcuts import render, redirect
from personalia.forms import fIndividu,fWarga
from django.db import transaction,IntegrityError
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages
from personalia.models import Warga

def tambahWarga(request):
    template_name = 'personalia/tambahWarga.html'
    form = (fIndividu,fWarga)

    if request.method == 'POST':
        cekform1 = fIndividu(request.POST)
        err_list = []
        if not cekform1.is_valid():
            errList = cekform1.errors.as_data().values()
            for e in errList :
                err_list.append(str(e[0]))

        cekform2 = fWarga(request.POST)
        if not cekform2.is_valid():
            errList = cekform1.errors.as_data().values()
            for e in errList :
                err_list.append(str(e[0]))

        if cekform1.is_valid() and cekform2.is_valid():
            with transaction.atomic():
                individu = cekform1.save()
                id_warga = str(individu.id_individu)
                id_warga = id_warga.zfill(10)
                warga = cekform2.save(commit=False)
                warga.individu = individu
                warga.id_warga = id_warga
                warga.save()
                messages.add_message(request, messages.SUCCESS, '''Berhasil menambah <b>{0}</b> ke dalam data anggota.
                Silahkan input kembali data lainnya'''.format(individu.nama.upper(),))
                return HttpResponseRedirect(reverse('personalia:tambahWarga'))
        else :
            #raise Exception, cekform1.errors.as_data()['__all__'][0]
            #raise Exception, cekform1.errors.as_json()
            #raise Exception, str(cekform1.errors.as_data().values()[0][0])
            #raise Exception, cekform1.errors.as_data().values()
            form = (cekform1,cekform2)
            individu = cekform1.clean()
            messages.add_message(request, messages.WARNING, '''Gagal menambahkan <b>{0}</b> ke dalam data anggota
            </br>{1}'''.format(individu['nama'].upper(),err_list))

    return render(request,template_name,{'form':form,})

def warga(request):
    anggota = Warga.objects.all()
    template_name = 'personalia/warga.html'
    #template_name = 'personalia/warga_jqgrid.html'
    return render(request,template_name,{'anggota':anggota})

templates/personalia/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static "images/favicon.ico" %}">

    <title>
      {% block title %}
        Aplikasi Anggota Koperasi
      {% endblock %}
    </title>
    <!-- Bootstrap core CSS -->
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
    <!-- Bootstrap theme -->
    <link href="{% static "css/bootstrap-theme.min.css" %}" rel="stylesheet">
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="{% static "assets/css/ie10-viewport-bug-workaround.css" %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static "personalia/theme.css" %}" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="{% static "assets/js/ie-emulation-modes-warning.js" %}"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <link href="{% static "css/jquery-ui.css" %}" rel="stylesheet">
  </head>

  <body>

    <!-- Fixed navbar -->
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'personalia:index' %}">Aplikasi Anggota Koperasi</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="#">Home</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Master <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li class="dropdown-header">Anggota</li>
                <li><a href="{% url 'personalia:warga' %}">Data Anggota</a></li>
                <li><a href="{% url 'personalia:tambahWarga' %}">Tambah Data Anggota</a></li>
                <li role="separator" class="divider"></li>
                <li class="dropdown-header">Pengurus</li>
                <li><a href="{% url 'personalia:pengurus' %}">Data Pengurus</a></li>
                <li><a href="{% url 'personalia:tambahAdmin' %}">Tambah Data Pengurus</a></li>
              </ul>
            </li>
            <li><a href="{% url 'personalia:laporan' %}">Laporan</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container theme-showcase" role="main">
    {% block content %}
      <h1>Hello ZIS</h1>
    {% endblock %}
    </div> <!-- /container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="{% static "assets/js/vendor/jquery.min.js" %}"><\/script>')</script>
    <script src="{% static "js/bootstrap.min.js" %}"></script>
    <script src="{% static "assets/js/docs.min.js" %}"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static "assets/js/ie10-viewport-bug-workaround.js" %}"></script>
  </body>
</html>

templates/personalia/tambahdata.html
{% extends "personalia/base.html" %}
{% load static %}

{% block title %}
  tambah data
{% endblock %}

{% block content %}
{% if messages %}
<div class="alert alert-success alert-dismissible" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  {% for message in messages %}
  {% if message.level == 30 %}
  <h3><span class="label label-danger">{{ message.tags|upper }}</span></h3>
  {% elif message.level == 25 %}
  <h3><span class="label label-success">{{ message.tags|upper }}</span></h3>
  {% else %}
  <h3><span class="label label-info">{{ message.tags|upper }}</span></h3>
  {% endif %}
  <p>
    {{message}}
  </p>
  {% endfor %}
</div>
{% endif %}
<div class="page-header">
  <h2><span class="glyphicon glyphicon glyphicon-plus" aria-hidden="true"></span> Tambah Data</h2>
</div>
<div class="form">
  <form method="post" class="form-horizontal" role="form">
    {% csrf_token %}
    {{ form.non_field_errors }}
    <div class="col-md-6">
      <div class="form-group">
        <label for="{{ form.0.nama.id_for_label }}" class="col-sm-4">Nama</label>
        <div class="col-sm-5">
          {{form.0.nama}}
        </div>
      </div>
      <div class="form-group">
        <label for="{{ form.0.jk.id_for_label }}" class="col-sm-4">Jenis Kelamin</label>
        <div class="col-sm-3">
          {{ form.0.jk }}
        </div>
      </div>
      <div class="form-group">
        <label for="{{ form.0.alamat_desa.id_for_label }}" class="col-sm-4">Alamat</label>
        <div class="col-sm-8">
          {{ form.0.alamat_desa }}
        </div>
      </div>
      <div class="form-group">
        <label for="{{ form.0.alamat_kec.id_for_label }}" class="col-sm-4"></label>
        <div class="col-sm-8">
          {{ form.0.alamat_kec }}
        </div>
      </div>
      <div class="form-group">
        <label for="{{ form.0.alamat_kabkot.id_for_label }}" class="col-sm-4"></label>
        <div class="col-sm-8">
          {{ form.0.alamat_kabkot }}
        </div>
      </div>
      <div class="form-group">
        <label for="{{ form.0.alamat_prov.id_for_label }}" class="col-sm-4"></label>
        <div class="col-sm-8">
          {{ form.0.alamat_prov }}
        </div>
      </div>
    </div>
    <div class="col-md-12 clearfix ">
      <div class="text-right">
        <button type="submit" class="btn btn-success"><span class="glyphicon glyphicon-save" aria-hidden="true"> SIMPAN</span></button>
        <button type="reset" class="btn btn-danger"><span class="glyphicon glyphicon-remove" aria-hidden="true"> BATAL</span></button>
      </div>
    </div>
  </form>
</div>

<script src="{% static "js/jquery.js" %}"></script>
<script src="{% static "js/jquery-ui.js" %}"></script>
<script type="text/javascript">
  $( "#id_tgl_lahir" ).datepicker();
  $( "#id_tgl_daftar" ).datepicker();
</script>
{% endblock %}

templates/personalia/tambahwarga.html
{% extends "personalia/base.html" %}
{% load static %}

{% block title %}
  tambah data
{% endblock %}

{% block content %}
{% if messages %}
<div class="alert alert-success alert-dismissible" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  {% for message in messages %}
  {% if message.level == 30 %}
  <h3><span class="label label-danger">{{ message.tags|upper }}</span></h3>
  {% elif message.level == 25 %}
  <h3><span class="label label-success">{{ message.tags|upper }}</span></h3>
  {% else %}
  <h3><span class="label label-info">{{ message.tags|upper }}</span></h3>
  {% endif %}
  <p>
    {{message|safe}}
  </p>
  {% endfor %}
</div>
{% endif %}
<div class="page-header">
  <h2><span class="glyphicon glyphicon glyphicon-plus" aria-hidden="true"></span> Tambah Data Anggota</h2>
</div>
<div class="form">
  <form method="post" class="form-horizontal" role="form">
    {% csrf_token %}
    {{ form.non_field_errors }}
    <div class="col-md-6">
      <div class="form-group">
        <label for="{{ form.0.nama.id_for_label }}" class="col-sm-4">Nama Anggota</label>
        <div class="col-sm-5">
          {{form.0.nama}}
        </div>
      </div>
      <div class="form-group">
        <label for="{{ form.0.tmpt_lahir.id_for_label }}" class="col-sm-4">Tempat / Tanggal Lahir</label>
        <div class="col-sm-8">
          <div class="row">
            <div class="col-xs-5">
              {{ form.0.tmpt_lahir }}
            </div>
            <div class="col-xs-5">
              {{ form.0.tgl_lahir }}
            </div>
          </div>
        </div>
      </div>
      <div class="form-group">
        <label for="{{ form.0.jk.id_for_label }}" class="col-sm-4">Jenis Kelamin</label>
        <div class="col-sm-3">
          {{ form.0.jk }}
        </div>
      </div>
      <div class="form-group">
        <label for="{{ form.0.alamat.id_for_label }}" class="col-sm-4">Alamat Lengkap</label>
        <div class="col-sm-8">
          {{ form.0.alamat }}
        </div>
      </div>
      <div class="form-group">
        <label for="{{ form.0.alamat_desa.id_for_label }}" class="col-sm-4"></label>
        <div class="col-sm-8">
          {{ form.0.alamat_desa }}
        </div>
      </div>
      <div class="form-group">
        <label for="{{ form.0.alamat_kec.id_for_label }}" class="col-sm-4"></label>
        <div class="col-sm-8">
          {{ form.0.alamat_kec }}
        </div>
      </div>
      <div class="form-group">
        <label for="{{ form.0.alamat_kabkot.id_for_label }}" class="col-sm-4"></label>
        <div class="col-sm-8">
          {{ form.0.alamat_kabkot }}
        </div>
      </div>
      <div class="form-group">
        <label for="{{ form.0.alamat_prov.id_for_label }}" class="col-sm-4"></label>
        <div class="col-sm-8">
          {{ form.0.alamat_prov }}
        </div>
      </div>
      <div class="form-group">
        <label for="{{ form.0.hp.id_for_label }}" class="col-sm-4">Nomor HP</label>
        <div class="col-sm-4">
          {{ form.0.hp }}
        </div>
      </div>
    </div>

    <div class="col-sm-6">
      <div class="form-group">
        <label for="{{ form.0.lulusan.id_for_label }}" class="col-sm-4">Pendidikan</label>
        <div class="col-sm-3">
          {{ form.0.lulusan }}
        </div>
      </div>
      <div class="form-group">
        <label for="{{ form.0.jenjang.id_for_label }}" class="col-sm-4">Jenjang Anggota</label>
        <div class="col-sm-3">
          {{ form.1.jenjang }}
        </div>
      </div>
      <div class="form-group">
        <label for="{{ form.0.tgl_daftar.id_for_label }}" class="col-sm-4">Tanggal Daftar</label>
        <div class="col-sm-4">
          {{ form.1.tgl_daftar }}
        </div>
      </div>
      <div class="form-group">
        <label for="{{ form.0.status_aktif.id_for_label }}" class="col-sm-4">Status Aktip</label>
        <div class="col-sm-3">
          {{ form.1.status_aktif }}
        </div>
      </div>
      <div class="form-group">
        <label for="{{ form.0.segmentasi.id_for_label }}" class="col-sm-4">Segmentasi</label>
        <div class="col-sm-4">
          {{ form.1.segmentasi }}
        </div>
      </div>
      <div class="form-group">
        <label for="{{ form.0.pangkal.id_for_label }}" class="col-sm-4">Leader</label>
        <div class="col-sm-4">
          {{ form.1.pangkal }}
        </div>
      </div>
      <div class="form-group">
        <label for="{{ form.0.warga_media.id_for_label }}" class="col-sm-4">Anngota Media</label>
        <div class="col-sm-1">
          {{ form.1.warga_media }}
        </div>
      </div>
      <div class="form-group">
        <label for="{{ form.0.keterangan.id_for_label }}" class="col-sm-4">Keterangan</label>
        <div class="col-sm-8">
          {{ form.1.keterangan }}
        </div>
      </div>
    </div>
    <div class="col-md-12 clearfix ">
      <div class="text-right">
        <button type="submit" class="btn btn-success"><span class="glyphicon glyphicon-save" aria-hidden="true"> SIMPAN</span></button>
        <button type="reset" class="btn btn-danger"><span class="glyphicon glyphicon-remove" aria-hidden="true"> BATAL</span></button>
      </div>
    </div>
  </form>
</div>

<script src="{% static "js/jquery.js" %}"></script>
<script src="{% static "js/jquery-ui.js" %}"></script>
<script type="text/javascript">
  $( "#id_tgl_lahir" ).datepicker();
  $( "#id_tgl_daftar" ).datepicker();
</script>
{% endblock %}

templates/personalia/tambahwarga_ori.html
{% extends "personalia/base.html" %}
{% load static %}

{% block title %}
  tambah data
{% endblock %}

{% block content %}
{% if msg %}
<div class="alert alert-danger" role="alert">
  <h4 class="alert-heading">Warning!!</h4>
  <p>{{msg}}</p>
</div>
{% else %}
<div class="alert alert-success" role="alert">
  <h4 class="alert-heading">Silahkan input data warga dengan benar</h4>
</div>
{% endif %}
<div class="page-header">
  <h2><span class="glyphicon glyphicon glyphicon-plus" aria-hidden="true"></span> Tambah Data Warga</h2>
</div>
<div class="form">
  <form action="." method="post" class="form-horizontal" role="form">
    {% csrf_token %}
    {{ form.non_field_errors }}
    <div class="col-md-6">
      <div class="form-group">
        <label for="{{ form.0.nama.id_for_label }}" class="col-sm-4">Nama</label>
        <div class="col-sm-5">
          {{form.0.nama}}
        </div>
      </div>
      <div class="form-group">
        <label for="{{ form.0.tmpt_lahir.id_for_label }}" class="col-sm-4">Tempat / Tanggal Lahir</label>
        <div class="col-sm-8">
          <div class="row">
            <div class="col-xs-5">
              {{ form.0.tmpt_lahir }}
            </div>
            <div class="col-xs-5">
              {{ form.0.tgl_lahir }}
            </div>
          </div>
        </div>
      </div>
      <div class="form-group">
        <label for="{{ form.0.jk.id_for_label }}" class="col-sm-4">Jenis Kelamin</label>
        <div class="col-sm-3">
          {{ form.0.jk }}
        </div>
      </div>
      <div class="form-group">
        <label for="{{ form.0.alamat.id_for_label }}" class="col-sm-4">Alamat</label>
        <div class="col-sm-8">
          {{ form.0.alamat }}
        </div>
      </div>
      <div class="form-group">
        <label for="{{ form.0.alamat_desa.id_for_label }}" class="col-sm-4"></label>
        <div class="col-sm-8">
          {{ form.0.alamat_desa }}
        </div>
      </div>
      <div class="form-group">
        <label for="{{ form.0.alamat_kec.id_for_label }}" class="col-sm-4"></label>
        <div class="col-sm-8">
          {{ form.0.alamat_kec }}
        </div>
      </div>
      <div class="form-group">
        <label for="{{ form.0.alamat_kabkot.id_for_label }}" class="col-sm-4"></label>
        <div class="col-sm-8">
          {{ form.0.alamat_kabkot }}
        </div>
      </div>
      <div class="form-group">
        <label for="{{ form.0.alamat_prov.id_for_label }}" class="col-sm-4"></label>
        <div class="col-sm-8">
          {{ form.0.alamat_prov }}
        </div>
      </div>
      <div class="form-group">
        <label for="{{ form.0.hp.id_for_label }}" class="col-sm-4">Nomor HP</label>
        <div class="col-sm-4">
          {{ form.0.hp }}
        </div>
      </div>
    </div>

    <div class="col-sm-6">
      <div class="form-group">
        <label for="{{ form.0.lulusan.id_for_label }}" class="col-sm-4">Pendidikan</label>
        <div class="col-sm-3">
          {{ form.0.lulusan }}
        </div>
      </div>
      <div class="form-group">
        <label for="{{ form.0.jenjang.id_for_label }}" class="col-sm-4">Lulusan</label>
        <div class="col-sm-3">
          {{ form.1.jenjang }}
        </div>
      </div>
      <div class="form-group">
        <label for="{{ form.0.tgl_daftar.id_for_label }}" class="col-sm-4">Tanggal Registrasi</label>
        <div class="col-sm-4">
          {{ form.1.tgl_daftar }}
        </div>
      </div>
      <div class="form-group">
        <label for="{{ form.0.status_aktif.id_for_label }}" class="col-sm-4">Status Aktip</label>
        <div class="col-sm-3">
          {{ form.1.status_aktif }}
        </div>
      </div>
      <div class="form-group">
        <label for="{{ form.0.segmentasi.id_for_label }}" class="col-sm-4">Segmentasi</label>
        <div class="col-sm-4">
          {{ form.1.segmentasi }}
        </div>
      </div>
      <div class="form-group">
        <label for="{{ form.0.pangkal.id_for_label }}" class="col-sm-4">Pangkal</label>
        <div class="col-sm-4">
          {{ form.1.pangkal }}
        </div>
      </div>
      <div class="form-group">
        <label for="{{ form.0.warga_media.id_for_label }}" class="col-sm-4">Warga Media</label>
        <div class="col-sm-1">
          {{ form.1.warga_media }}
        </div>
      </div>
      <div class="form-group">
        <label for="{{ form.0.keterangan.id_for_label }}" class="col-sm-4">Keterangan</label>
        <div class="col-sm-8">
          {{ form.1.keterangan }}
        </div>
      </div>
    </div>
    <div class="col-md-12 clearfix ">
      <div class="text-right">
        <button type="submit" class="btn btn-success"><span class="glyphicon glyphicon-save" aria-hidden="true"> SIMPAN</span></button>
        <button type="reset" class="btn btn-danger"><span class="glyphicon glyphicon-remove" aria-hidden="true"> BATAL</span></button>
      </div>
    </div>
  </form>
</div>

<script src="{% static "js/jquery.js" %}"></script>
<script src="{% static "js/jquery-ui.js" %}"></script>
<script type="text/javascript">
  $( "#id_tgl_lahir" ).datepicker();
  $( "#id_tgl_daftar" ).datepicker();
</script>
{% endblock %}

templates/personalia/warga.html
{% extends "personalia/base.html" %}

{% block title %}
  data warga
{% endblock %}

{% block content %}
<div class="page-header">
  <h1><span class="glyphicon glyphicon-book" aria-hidden="true"></span> Data Anggota</h1>
</div>
<div class="">
  <table class="table table-bordered table-striped">
    {% block table %}
    <thead>
      <tr class="something">
        <th class="col-md-2">No</th>
        <th class="col-md-4">ID Anggota</th>
        <th class="col-md-4">Nama</th>
        <th class="col-md-2">Jenis Kelamin</th>
        <th class="col-md-2">Jenjang Karir</th>
        <th class="col-md-2">Leader</th>
      </tr>
    </thead>
    <tbody>
      {% for anggota in anggota %}
      {{anggota}}
      <tr class="something">
        <td class="col-sm-2">{{forloop.counter}}</td>
        <td class="col-md-4">{{anggota.id_warga|upper}}</td>
        <td class="col-md-4">{{anggota.individu.nama|title}}</td>
        <td class="col-md-4">{{anggota.individu.get_jk_display}}</td>
        <td class="col-md-4">{{anggota.get_jenjang_display}}</td>
        <td class="col-md-4">{{anggota.pangkal.nama|title}}</td>
      </tr>
      {% endfor %}
    </tbody>
    {% endblock %}
  </table>
</div>
{% endblock %}